---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cdn-proxy
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          configmap.reloader.stakater.com/reload: &configmap cdn-proxy-configmap
        containers:
          main:
            image:
              repository: public.ecr.aws/nginx/nginx
              tag: "1.27.1"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: external-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.monosense.io
        hosts:
          - host: &host ${HOSTNAME}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls: [hosts: [*host]]
    persistence:
      nginx-config:
        enabled: true
        type: "custom"
        globalMounts:
          - path: /etc/nginx/nginx.conf
            subPath: nginx-config
        volumeSpec:
          configMap:
            name: *configmap
