---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdn-proxy
  namespace: flux-system
spec:
  path: ./kubernetes/apps/network/cdn-proxy/app
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: prod-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname cdn-proxy
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: static.monosense.io
