---
apiVersion: batch/v1
kind: Job
metadata:
  name: "${jobName}"
  namespace: "default"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: ${node}
      containers:
        - name: disk-wipe
          image: ghcr.io/onedr0p/alpine:3.19.1@sha256:3fbc581cb0fe29830376161ae026e2a765dcc11e1747477fe9ebf155720b8638
          securityContext:
            privileged: true
          resources: {}
          command: ["/bin/sh", "-c"]
          args:
            - apk add --no-cache sgdisk util-linux parted device-mapper;
              sgdisk --zap-all ${cephDisk};
              blkdiscard ${cephDisk};
              dd if=/dev/zero bs=1M count=10000 oflag=direct of=${cephDisk};
              nsenter --mount=/proc/1/ns/mnt partprobe ${cephDisk};
              nsenter --mount=/proc/1/ns/mnt dmsetup remove_all;
          volumeMounts:
            - name: dev-disk
              mountPath: /dev/disk
      volumes:
        - name: dev-disk
          hostPath:
            path: /dev/disk
